sudo: required
services:
    - docker

before_install:
    - docker build -t willgray/docker-react -f Dockerfile.dev .

script:
    - docker run willgray/docker-react npm run test -- --coverage